"""Rebuild the all-pillar tables inside output/INSTRUMENT_NOTES.md.

  python build_notes.py          rewrite the generated section
  python build_notes.py --check  exit 1 if the section is out of date; write nothing

INSTRUMENT_NOTES.md is the plain-language companion to the codebook. Its narrative is edited in
place; the section between the two GENERATED markers is rebuilt here so it cannot drift from the
files it describes:

  one line per indicator      asks / the one thing to not get wrong: scripts/data/notes_table.yaml
                              scores, tier, polarity, level:         output/indicators.yaml
                              evidence type:                         output/indicator_order.yaml
  where the evidence lives    the "Where the measures live" banner above each pillar in indicators.yaml
  reviewed label flags        output/gold/gold_set.jsonl
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict

import yaml

from codebook_file import split
from rdtii_examples import DATA, REPO

OUT = REPO / "output"
NOTES = OUT / "INSTRUMENT_NOTES.md"
TABLE = DATA / "notes_table.yaml"
BEGIN = "<!-- BEGIN GENERATED by scripts/build_notes.py: do not edit between the markers -->"
END = "<!-- END GENERATED -->"


def cell(s) -> str:
    return re.sub(r"\s+", " ", str(s)).replace("|", "\\|").strip()


def build() -> str:
    text = (OUT / "indicators.yaml").read_text(encoding="utf-8")
    cb = split(text)
    blocks = {str(b["id"]): b for b in yaml.safe_load(text)["indicators"]}
    order = yaml.safe_load((OUT / "indicator_order.yaml").read_text(encoding="utf-8"))
    table = {str(k): v for k, v in (yaml.safe_load(TABLE.read_text(encoding="utf-8")) or {}).items()}
    entries = [e for e in order["indicators"] if e["status"] == "in_scope"]
    missing = [e["id"] for e in entries if e["id"] not in table]
    if missing:
        raise SystemExit(f"notes_table.yaml has no entry for {missing}")
    gold = [json.loads(ln) for ln in (OUT / "gold" / "gold_set.jsonl").read_text(encoding="utf-8").splitlines()]

    by_pillar = defaultdict(list)
    for e in entries:
        by_pillar[e["pillar"]].append(e)
    labels = {e["pillar"]: e["pillar_label"] for e in entries}
    tiers = Counter(b["tier"] for b in blocks.values())

    out = [BEGIN, "",
           "## 8. Every indicator in one breath",
           "",
           f"All {len(entries)} in-scope indicators, in host order. Tiers: "
           + ", ".join(f"{t} {n}" for t, n in sorted(tiers.items())) + ". Marks: *inverted* means an absent "
           "framework scores 1; *economy* means the indicator is answered once per economy; *practice* means "
           "evidence of practice is allowed (Internal Guide p.8).",
           ""]
    for p in sorted(by_pillar):
        out += [f"### {labels[p]}", "",
                "| ID | Asks | Scores | Marks | The one thing to not get wrong |",
                "| :---- | :---- | :---- | :---- | :---- |"]
        for e in by_pillar[p]:
            b, t = blocks[e["id"]], table[e["id"]]
            marks = [f"tier {b['tier']}"]
            if b.get("polarity") == "inverted": marks.append("inverted")
            if b.get("level") == "economy": marks.append("economy")
            if e.get("evidence") == "practice": marks.append("practice")
            scores = " / ".join(f"{v:g}" for v in b["scoring"]["values"])
            out.append(f"| {e['id']} | {cell(t['asks'])} | {scores} | {', '.join(marks)} | {cell(t['not_to_get_wrong'])} |")
        out.append("")

    out += ["## 9. Where the evidence lives, by pillar", "",
            "The kinds of law each pillar's measures are found in. This is what triage and the prefilter have to",
            "reach; an act's name alone rarely says which indicator it carries.", ""]
    for p in sorted(by_pillar):
        banner = cb.banners.get(p, "")
        m = re.search(r"Where the measures live:(.*?)(?=\n# -{10,})", banner, flags=re.S)
        where = re.sub(r"\s*\n#\s*", " ", m.group(1)).strip() if m else "not written yet"
        out.append(f"- **{labels[p]}.** {where}")
    out.append("")

    reviewed = [g for g in gold if (g.get("label_flag") or {}).get("status") in ("suspect", "advisory")]
    per_ind = defaultdict(Counter)
    for g in reviewed:
        per_ind[g["indicator"]][g["label_flag"]["status"]] += 1
    basis = Counter(g["label_flag"].get("basis") for g in reviewed)
    out += ["## 10. Reviewed label flags, all pillars", "",
            f"{len(reviewed)} host rows carry a reviewed flag: "
            + ", ".join(f"{n} from {b}" for b, n in sorted(basis.items(), key=lambda x: str(x[0]))) + ".",
            "A *suspect* row contradicts an explicit host rule or is filed under the wrong indicator, and is never",
            "used as an exemplar. An *advisory* row is defensible but rests on a judgement. The reasons are in",
            "`gold/gold_set.jsonl` (`label_flag.reason`). Flags outside pillars 6-7 were set while drafting and",
            "have not been confirmed by a person.", "",
            "| Indicator | Suspect | Advisory |", "| :---- | ----: | ----: |"]
    for e in entries:
        c = per_ind.get(e["id"])
        if c:
            out.append(f"| {e['id']} | {c.get('suspect', 0)} | {c.get('advisory', 0)} |")
    out += ["", END]
    return "\n".join(out) + "\n"


def main() -> None:
    notes = NOTES.read_text(encoding="utf-8")
    section = build()
    if BEGIN in notes:
        new = notes[: notes.index(BEGIN)] + section + notes[notes.index(END) + len(END):].lstrip("\n")
    else:
        new = notes.rstrip("\n") + "\n\n" + section
    if "--check" in sys.argv:
        print("INSTRUMENT_NOTES.md generated section is " + ("current" if new == notes else "OUT OF DATE"))
        sys.exit(0 if new == notes else 1)
    NOTES.write_text(new, encoding="utf-8", newline="\n")
    print(f"wrote the generated section of {NOTES.relative_to(REPO)}")


if __name__ == "__main__":
    main()
