"""Stages B+C — build output/signatures/<ID>.yaml for every in-scope indicator.

Per indicator:
  keywords            curated (not mined), recall-biased lexical terms (BM25/keyword leg)
  definition_text     canonical text to embed (dense leg) — mirrors the codebook block
  exemplar_law_types  families of law that carry the indicator
  scope_patterns      horizontal-vs-sectoral signals
  negative_signals    look-alikes that belong to a sibling indicator (traps)
  exemplars[]         real coded rows from the host workbooks (Round 1 SG/AU/MY + Round 2
                      CN/IN/ID/LA/MN/RU/TH), curated for score spread and trap teaching;
                      rows flagged 'suspect' in the gold set are never used

Content lives in data files, not in this script (finale change, 2026-09-13):
  scripts/data/signature_spec.yaml      keywords, definition text, law types, scope, negatives
  scripts/data/curated_exemplars.yaml   (sheet, row, teaching note) per indicator

Exemplar 'impact' text is the host researchers' own evidence summary, trimmed at a sentence
boundary (<=650 chars). Verbatim statute text is NOT available in the workbooks.
Output files are named by decimal ID (6.1.yaml, 12.4.1.yaml); legacy P6-I1.yaml files are removed.
"""
from __future__ import annotations

import re
import sys

import yaml

from indicator_ids import normalize
from rdtii_examples import DATA, REPO, load_all, trim_sentence

OUT_DIR = REPO / "output" / "signatures"
ORDER = REPO / "output" / "indicator_order.yaml"
CODEBOOK = REPO / "output" / "indicators.yaml"
LEGACY_FILE = re.compile(r"^P\d{1,2}-I\d{1,2}\.yaml$")


def tiers() -> dict[str, str]:
    doc = yaml.safe_load(CODEBOOK.read_text(encoding="utf-8"))
    return {normalize(b["id"]): b.get("tier", "?") for b in doc["indicators"]}


def main() -> int:
    order = yaml.safe_load(ORDER.read_text(encoding="utf-8"))
    in_scope = [e["id"] for e in order["indicators"] if e["status"] == "in_scope"]
    spec = {normalize(k): v for k, v in yaml.safe_load((DATA / "signature_spec.yaml").read_text(encoding="utf-8")).items()}
    curated = {normalize(k): v for k, v in yaml.safe_load((DATA / "curated_exemplars.yaml").read_text(encoding="utf-8")).items()}
    tier_of = tiers()
    rows = {(r["sheet"], r["row"]): r for r in load_all()}
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for p in OUT_DIR.glob("*.yaml"):
        if LEGACY_FILE.match(p.name) or normalize(p.stem) not in in_scope:
            p.unlink()

    missing = []
    for ind in in_scope:
        if ind not in spec or ind not in curated:
            missing.append(ind)
            continue
        s = spec[ind]
        exemplars = []
        for x in curated[ind]:
            r = rows.get((x["sheet"], x["row"]))
            assert r is not None, f"{ind}: ({x['sheet']},{x['row']}) not in the workbooks"
            assert r["indicator"] == ind, f"{ind}: ({x['sheet']},{x['row']}) is {r['indicator']}"
            assert not r["strikethrough"], f"{ind}: ({x['sheet']},{x['row']}) is struck through"
            exemplars.append({
                "economy": r["economy"],
                "law": trim_sentence(r["law"], 200),
                "coverage": r["coverage"],
                "score": r["raw_score"],
                "impact": trim_sentence(r["impact"], 650),
                "url": (r["urls"][0] if r["urls"] else None),
                "teaching_note": x["note"],
                "gold_id": r["gold_id"],
                "provenance": {"workbook": r["source"], "sheet": x["sheet"], "row": x["row"]},
            })
        doc = {
            "indicator": ind,
            "name": s["name"],
            "tier": tier_of.get(ind, "?"),
            "instrument_version": "2.1.0",
            "keywords": s["keywords"],
            "definition_text": re.sub(r"\s+", " ", s["definition_text"]).strip(),
            "exemplar_law_types": s["exemplar_law_types"],
            "scope_patterns": s["scope_patterns"],
            "negative_signals": s["negative_signals"],
            **({"spec_note": s["spec_note"]} if s.get("spec_note") else {}),
            "exemplars": exemplars,
        }
        path = OUT_DIR / f"{ind}.yaml"
        with path.open("w", encoding="utf-8", newline="\n") as f:
            f.write("# Generated by scripts/build_signatures.py — edit scripts/data/signature_spec.yaml\n"
                    "# and scripts/data/curated_exemplars.yaml, then re-run; do not hand-edit.\n")
            yaml.safe_dump(doc, f, allow_unicode=True, sort_keys=False, width=100)
    built = len(in_scope) - len(missing)
    print(f"signatures: {built}/{len(in_scope)} built"
          + (f"; missing spec or exemplars for {missing}" if missing else ""))
    return 1 if missing and "--allow-missing" not in sys.argv else 0


if __name__ == "__main__":
    sys.exit(main())
