"""Label-flag report: every flagged gold row, by status, with the reason.

Usage: python scripts/report_flags.py [--out PATH]   (markdown to stdout, or to PATH)
Feeds the evidence folder: which host rows the instrument treats with care, why, and who made the call.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from datetime import date
from pathlib import Path

from rdtii_examples import REPO

OUT = REPO / "output"
MEANING = {
    "suspect": "Reviewed: the score contradicts an explicit host rule, or the row is filed under the wrong indicator. Never an exemplar",
    "advisory": "Reviewed: defensible, but rests on a judgement the reader should know about",
    "host_marked": "The host's own data verification marked the row \"Not correct\" (Thailand sheet). Never an exemplar",
    "candidate": "Machine check only, unreviewed",
}
BASIS = {"round1_review": "Round 1 review (pillars 6-7, July 2026)",
         "drafting_review_2026-10-04": "drafting review of 4 October 2026 (other pillars; not confirmed by a person)"}


def cell(s, n: int = 10_000) -> str:
    return re.sub(r"\s+", " ", str(s or "")).replace("|", "\\|").strip()[:n]


def main() -> None:
    gold = [json.loads(ln) for ln in (OUT / "gold" / "gold_set.jsonl").read_text(encoding="utf-8").splitlines() if ln.strip()]
    flagged = [g for g in gold if g.get("label_flag")]
    n = Counter(g["label_flag"]["status"] for g in flagged)
    rounds = Counter(g["baseline_round"] for g in gold)
    basis = Counter(g["label_flag"].get("basis") for g in flagged if g["label_flag"]["status"] in ("suspect", "advisory"))
    lines = [f"# Gold-set label flags — generated {date.today().isoformat()}", "",
             f"Gold set: {len(gold)} rows (Round 1 {rounds.get('round1', 0)}, Round 2 {rounds.get('round2', 0)}), "
             f"all pillars, {len({g['economy'] for g in gold})} economies. {len(flagged)} rows carry a flag.",
             "Generated by `scripts/report_flags.py` from `output/gold/gold_set.jsonl`.", "",
             "| Status | Rows | Meaning |", "| :---- | ----: | :---- |"]
    for s in ("suspect", "advisory", "host_marked", "candidate"):
        lines.append(f"| {s} | {n.get(s, 0)} | {MEANING[s]} |")
    lines += ["", "Who made the reviewed calls (suspect and advisory):", ""]
    lines += [f"- {BASIS.get(b, b)}: {c} rows" for b, c in sorted(basis.items(), key=lambda x: str(x[0]))]
    lines += ["", "## Reviewed flags by indicator", "", "| Indicator | Suspect | Advisory | Rows in the gold set |",
              "| :---- | ----: | ----: | ----: |"]
    per = Counter((g["indicator"], g["label_flag"]["status"]) for g in flagged)
    total = Counter(g["indicator"] for g in gold)
    seen = []
    for g in gold:
        if g["indicator"] not in seen:
            seen.append(g["indicator"])
    for ind in seen:
        if per.get((ind, "suspect")) or per.get((ind, "advisory")):
            lines.append(f"| {ind} | {per.get((ind, 'suspect'), 0)} | {per.get((ind, 'advisory'), 0)} | {total[ind]} |")
    for s in ("suspect", "advisory", "host_marked", "candidate"):
        rows = [g for g in flagged if g["label_flag"]["status"] == s]
        lines += ["", f"## {s} ({len(rows)})", "", "| gold_id | Indicator | Score | Law | Reason / host action |",
                  "| :---- | :---- | :---- | :---- | :---- |"]
        for g in rows:
            lines.append(f"| {g['gold_id']} | {g['indicator']} | {cell(g['raw_score'])} | {cell(g['law'], 70)} | "
                         f"{cell(g['label_flag']['reason'])} |")
    hv = Counter(((g.get("host_verification") or {}).get("feedback") or "").strip() for g in gold
                 if (g.get("host_verification") or {}).get("feedback"))
    lines += ["", "## Host verification coverage", "",
              "Rows carrying the host's own verification feedback: "
              + (", ".join(f"{k}: {v}" for k, v in sorted(hv.items())) or "none") + "."]
    text = "\n".join(lines) + "\n"
    if "--out" in sys.argv:
        Path(sys.argv[sys.argv.index("--out") + 1]).write_text(text, encoding="utf-8", newline="\n")
    else:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
