"""Roll-up fields report: per block, the count rule in one line and what an absence scores.

Usage: python scripts/report_rollup_fields.py [--out PATH]   (markdown to stdout, or to PATH)
Feeds the evidence folder and the reply to the mapping stage (requests R5 and R6, decision D17).
Read from output/indicators.yaml, so it reports what the blocks carry, not what the data file says.
"""
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

import yaml

from rdtii_examples import REPO

OUT = REPO / "output"
WHY_NULL = {"inverted": "inverted: the absence is the top score", "evidence": "a 0 needs positive evidence",
            "outside": "the answer is outside the legislation searched"}


def cell(s) -> str:
    return re.sub(r"\s+", " ", str(s or "")).replace("|", "\\|").strip()


def num(x) -> str:
    return f"{x:g}"


def rule_line(r: dict) -> str:
    counted = " or ".join(num(x) for x in r["counted_scores"])
    if r["method"] == "sum":
        return f"add each law's score, stop at {num(r['cap'])}"
    steps = "; ".join(f"{t['at_least']} or more laws at {counted} give {num(t['score'])}" for t in r["thresholds"])
    return f"{steps}; otherwise the highest verified score"


def null_reason(b: dict) -> str:
    if b.get("polarity") == "inverted":
        return WHY_NULL["inverted"]
    return WHY_NULL["evidence"] if str(b["id"]) == "11.2" else WHY_NULL["outside"]


def main() -> None:
    blocks = yaml.safe_load((OUT / "indicators.yaml").read_text(encoding="utf-8"))["indicators"]
    ruled = [b for b in blocks if "count_rule" in b]
    unscored = [b for b in blocks if b["absence_score"] is None]
    scored = [b for b in blocks if b["absence_score"] is not None]
    lines = [f"# Roll-up fields — generated {date.today().isoformat()}", "",
             f"Generated by `scripts/report_rollup_fields.py` from `output/indicators.yaml`. {len(blocks)} blocks: "
             f"`absence_score` is a value on {len(scored)} and null on {len(unscored)}; `count_rule` is on {len(ruled)}.",
             "", "## Count rules", "",
             "For one economy and one indicator, take each law's highest verified score, then apply the rule.",
             "",
             "| Block | What the host counts | Rule | Absence | Computable from distinct laws? |",
             "| :---- | :---- | :---- | :---- | :---- |"]
    for b in ruled:
        r = b["count_rule"]
        need = "; ".join(f"needs `{n['fact']}` on each verdict: {cell(n['why'])}" for n in r["needs"])
        a = "unscored" if b["absence_score"] is None else num(b["absence_score"])
        lines.append(f"| {b['id']} | {cell(r['counts'])} | {rule_line(r)} | {a} | "
                     f"{'No: ' + need if need else 'Yes'} |")
    lines += ["", "## What an absence scores", "",
              "| Absence | Blocks | Which | Why |", "| :---- | ----: | :---- | :---- |"]
    for value in sorted({b["absence_score"] for b in scored}):
        ids = [str(b["id"]) for b in scored if b["absence_score"] == value]
        lines.append(f"| {num(value)} | {len(ids)} | {', '.join(ids)} | no qualifying measure is the block's "
                     f"{num(value)} branch, and the host scores an absence of specific measures {num(value)} |")
    for why in WHY_NULL.values():
        ids = [str(b["id"]) for b in unscored if null_reason(b) == why]
        lines.append(f"| unscored (null) | {len(ids)} | {', '.join(ids)} | {why} |")
    lines += ["", "## Every block", "", "| Block | Absence | Basis |", "| :---- | :---- | :---- |"]
    for b in blocks:
        a = "unscored" if b["absence_score"] is None else num(b["absence_score"])
        lines.append(f"| {b['id']} | {a} | {cell(b['absence_basis'])} |")
    text = "\n".join(lines) + "\n"
    if "--out" in sys.argv:
        Path(sys.argv[sys.argv.index("--out") + 1]).write_text(text, encoding="utf-8", newline="\n")
    else:
        sys.stdout.reconfigure(encoding="utf-8")
        print(text, end="")


if __name__ == "__main__":
    main()
